CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,

                       CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE accounts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          user_id BIGINT NOT NULL,

                          CONSTRAINT fk_accounts_user
                              FOREIGN KEY (user_id)
                                  REFERENCES users (id),

                          CONSTRAINT uk_accounts_user_name
                              UNIQUE (user_id, name)
);

CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(100) NOT NULL,
                            user_id BIGINT NOT NULL,

                            CONSTRAINT fk_categories_user
                                FOREIGN KEY (user_id)
                                    REFERENCES users (id),

                            CONSTRAINT uk_categories_user_name
                                UNIQUE (user_id, name)
);

CREATE TABLE transactions (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              description VARCHAR(255) NOT NULL,
                              amount NUMERIC(19, 2) NOT NULL,
                              date DATE NOT NULL,
                              type VARCHAR(20) NOT NULL,
                              account_id BIGINT NOT NULL,
                              category_id BIGINT NOT NULL,

                              CONSTRAINT fk_transactions_account
                                  FOREIGN KEY (account_id)
                                      REFERENCES accounts (id),

                              CONSTRAINT fk_transactions_category
                                  FOREIGN KEY (category_id)
                                      REFERENCES categories (id),

                              CONSTRAINT chk_transactions_amount_positive
                                  CHECK (amount > 0),

                              CONSTRAINT chk_transactions_type
                                  CHECK (type IN ('INCOME', 'EXPENSE'))
);
