spring.application.name=financeManager

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/finance_manager}
spring.datasource.username=finance_manager
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-seconds=3600

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
