spring.application.name=financeManager

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/finance_manager}
spring.datasource.username=finance_manager
spring.datasource.password=${DB_PASSWORD}
